name: text_form_validator
description: Provides a simple way to combine validation functions, failing and
  providing the most informative error to the user.
version: 1.0.5
homepage: https://github.com/Guthers/flutter_form_validation

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
